### ISSUE TITLE
How to create a new model from prestashop¿

### ISSUE THREAD

**Issue by alainpc** [OCA/connector-prestashop#105]
Hi ,

I want to get de history of order states from prestashop . I realize that this model is not imported on the connector so I wanted to know what are the steps to import them. If I want to create a new model of prestashop object, which objects(importer , adapter ..) have to been created? 

Thanks in advance

**Comment by FFernandez-PlanetaTIC** [comment]
Hi @alainpc ,

You can take a look to at the connector documentation:
- [Code overview](http://odoo-connector.com/guides/code_overview.html)
- [Connector concepts](http://odoo-connector.com/guides/concepts.html)

With this you will understand better how the Prestashop connector works.

Regards!

**Comment by alainpc** [comment]
Thank you so much @FFernandez-PlanetaTIC !

But I'm struggling with this. I can't registry my new component, when I try to import I get this error:

'NoComponentError: No component found for collection 'prestashop.backend', usage 'batch.importer', model_name 'sale.order.state.history'.'

Where the component has to been registred?

Thanks
