### ISSUE TITLE
No work_on method defined for the prestashop.backend

### ISSUE THREAD

**Issue by omalbastin** [OCA/connector-prestashop#107]
I was going through the code and I can't find the work_on method which initiates the api call.

**Comment by pedrobaeza** [comment]
If you have an specific issue, please report it, but don't try to find non existing issues looking at code.

**Comment by omalbastin** [comment]
Sorry. My bad. It is not an issue. I saw in magento connector using work_on method. I was checking it in prestashop and cant find it
