### ISSUE TITLE
Error PrestaShop-Odoo connector Odoo 8

### ISSUE THREAD

**Issue by witoszek** [OCA/connector-prestashop#121]
Hello 

I've got these error:  File "/etc/odoo/custom/connector_prestashop/unit/importer.py", line 423, in _split_per_language
    raise FailedJobError(
FailedJobError: No language mapping defined. Run "Synchronize base data".

How can i configured? Do i need to rewrite the code?

the version that i use is Odoo 8.

**Comment by bodi000** [comment]
Hello,

Your question would be better treated in a forum, not here. But did you configure your PS connection? Address, API key? Can you connect to the shop? Did you get the base data in odoo?

Good luck!
B

**Comment by witoszek** [comment]
Hello thanks to answer. I ve connect ps with api and apikey. I can conect  ps with Odoo , but i couldn't to sync data base. The problem  is no langage mapping  defined.

**Comment by pedrobaeza** [comment]
Run "Synchronize base data" as stated in the message.

**Comment by witoszek** [comment]
Yes i do it but say language mapped not defined, and fail the cron jobs.
And i can not get base data in odoo

**Comment by witoszek** [comment]
Hello How can i fix An ERP record with same ID already exists on PrestaShop. and FailedJobError: No language mapping defined. Run "Synchronize base data".?
