### ISSUE TITLE
[v10.0]Dummy package used in requirements.txt

### ISSUE THREAD

**Issue by adamwojt** [OCA/connector-prestashop#128]
https://github.com/OCA/connector-prestashop/blob/af05419e40bfc9fe6a738fb6b60bde2b4cb7c1e7/requirements.txt#L4

See here : https://pypi.org/project/bs4/
Better to change to `beautifulsoup4` in case this stops being maintained.

**Comment by FFernandez-PlanetaTIC** [comment]
Thank you @adamwojt
