### ISSUE TITLE
[10] Misleading comment for dependencies. 

### ISSUE THREAD

**Issue by adamwojt** [OCA/connector-prestashop#129]
https://github.com/OCA/connector-prestashop/blob/af05419e40bfc9fe6a738fb6b60bde2b4cb7c1e7/connector_prestashop/__manifest__.py#L18

`base_multi_image ` comes from server-tools

**Comment by pedrobaeza** [comment]
In fact I think it should be `product_multi_image`.

**Comment by adamwojt** [comment]
@pedrobaeza Thank you :)

**Comment by FFernandez-PlanetaTIC** [comment]
See https://github.com/akretion/connector-prestashop/pull/8#discussion_r329587052
