### ISSUE TITLE
product_images or product_images_olb?

### ISSUE THREAD

**Issue by scigghia** [OCA/connector-prestashop#13]
hi,
in **openerp**.py i see product_images, but i've found product_images_olb in git:product-attribute
are they the same?

[6.1]

**Comment by pedrobaeza** [comment]
Which version? 7.0? I see only the first one: https://github.com/OCA/product-attribute/tree/7.0/product_images

**Comment by scigghia** [comment]
[6.1]

**Comment by pedrobaeza** [comment]
Well, I don't know that version, but I suppose the correct one is the dependency, not the other

**Comment by scigghia** [comment]
sure, but in the product-attribute there isn't product_images for 6.1
i'm a bit confused...

**Comment by pedrobaeza** [comment]
I can't help you. Maybe @liebana can...

**Comment by scigghia** [comment]
https://www.odoo.com/apps/modules/6.1/product_images/

**Comment by pedrobaeza** [comment]
For v8, it's https://github.com/OCA/product-attribute/tree/8.0/product_multi_image
