### ISSUE TITLE
Is this repository abandoned ?

### ISSUE THREAD

**Issue by estekadigital** [OCA/connector-prestashop#149]
Hello, 

Is this repository abandoned or it has been moved to odoo connector? I'd need a Prestashop bridge for 13.0 or 14.0, I was thinking to migrate it from Tecnativas's https://github.com/Tecnativa/connector-prestashop/tree/12.0-mig-connector_prestashop

Thanks in advance.

**Comment by pedrobaeza** [comment]
https://github.com/OCA/connector-prestashop/pull/147
