### ISSUE TITLE
Prestashop - Odoo - Link Orders problem

### ISSUE THREAD

**Issue by PILLETHITECH** [OCA/connector-prestashop#156]
## Module
Prestashop Connector / Job Queue /  Import a record from PrestaShop

## Describe the bug
<html>
<body>

Hi Everyone
I try to install prestashop connector to link my odoo community to a new installation of Prestashop.
Products, variants, clients are synchronise ! 

But odooBot has an error with Orders.

Could you help me please ?

PrestaShop-Odoo connector : V14.0.1.0.0
Prestashop : V1.7.5.0

Exception Information
--

Exception:prestapyt.prestapyt.PrestaShopWebServiceError

  File "/usr/local/lib/python3.7/dist-packages/prestapyt/prestapyt.py", line 200, in _check_status_code
    ps_error_code=ps_error_code,
prestapyt.prestapyt.PrestaShopWebServiceError: 'Resource of type "order_discounts" does not exists. Did you mean: "order_histories"? The full list is: "addresses", "carriers", "cart_rules", "carts", "categories", "combinations", "configurations", "contacts", "content_management_system", "countries", "currencies", "customer_messages", "customer_threads", "customers", "customizations", "deliveries", "employees", "groups", "guests", "image_types", "images", "languages", "manufacturers", "messages", "order_carriers", "order_details", "order_histories", "order_invoices", "order_payments", "order_slip", "order_states", "orders", "price_ranges", "product_customization_fields", "product_feature_values", "product_features", "product_option_values", "product_options", "product_suppliers", "products", "search", "shop_groups", "shop_urls", "shops", "specific_price_rules", "specific_prices", "states", "stock_availables", "stock_movement_reasons", "stock_movements", "stocks", "stores", "suppliers", "supply_order_details", "supply_order_histories", "supply_order_receipt_histories", "supply_order_states", "supply_orders", "tags", "tax_rule_groups", "tax_rules", "taxes", "translated_configurations", "warehouse_product_locations", "warehouses", "weight_ranges", "zones"'
 

</body>
</html>

## To Reproduce
**Affected versions**:

1.
2.
3.

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by PILLETHITECH** [comment]
I have the same issue directly with Postman.

So i think that the api structure of prestashop /api/order_discounts does not exist.

I will try to install another Version of Prestashop

**Comment by flotho** [comment]
PS change the order_discount ressources to another one .
Latest connector reflect this https://github.com/OCA/connector-prestashop/blob/14.0/connector_prestashop/components/version_key.py#L133
adpat your PS key and retry
