### ISSUE TITLE
Not connect to Prestashop

### ISSUE THREAD

**Issue by alvarosalinero** [OCA/connector-prestashop#157]
Hello,

I am trying to connect with prestashop.

I indicate the URL and the Key and it returns the following error:

```
Connection failed

Authentication Error:

'Unauthorized'
```

That could be happening?

Thanks.

All the best,

Álvaro

**Comment by jesusVMayor** [comment]
Try to add this into the prestashop .htaccess

```
RewriteEngine on
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule . - [E=HTTP_AUTHORIZATION:%1]
```

**Comment by alvarosalinero** [comment]
> Try to add this into the prestashop .htaccess
> 
> ```
> RewriteEngine on
> RewriteCond %{HTTP:Authorization} ^(.*)
> RewriteRule . - [E=HTTP_AUTHORIZATION:%1]
> ```

Thank you @jesusVMayor. It´s OK for me
