### ISSUE TITLE
Does not synchronize with Prestashop

### ISSUE THREAD

**Issue by alvarosalinero** [OCA/connector-prestashop#158]
Hello,

I am trying to bring any information (products, orders, contacts...) to Odoo from Prestashop but it always stays in "pending" status in the Queue Job.

Why is this happening to me?

Thank you

**Comment by flachica** [comment]
You must read all related with queue_job. Follow [this](https://github.com/OCA/connector-prestashop/tree/14.0/connector_prestashop#steps-in-odoo) link
