### ISSUE TITLE
Odoo breaks after run pip install -r requirements.txt

### ISSUE THREAD

**Issue by DGEAPerez** [OCA/connector-prestashop#20]
Hello, 

I've a fresh and running install of Odoo in a CentOS 6.7 (Virtual Box) which has a copy of Prestashop from a production environment...

I followed the steps from here for install Odoo:  
https://odootricks.wordpress.com/2014/09/30/installing-odoo-8-on-centos-6-with-virtual-python-install/

And "snapshooted" the state of Virtual Box... 

Then tryed to follow your guide, and using the akretyon prestapyt or running the pip for requirements from your sources, results in Odoo stops works...

Here is the output from install procedure from pip

``` bash
(odoo) [odoo@mercurio connector-prestashop-8.0]$ pip install -r requirements.txt
Obtaining prestapyt from git+git://github.com/akretion/prestapyt.git#egg=prestapyt (from -r requirements.txt (line 1))
  Cloning git://github.com/akretion/prestapyt.git to /home/odoo/odoo/src/prestapyt
Collecting requests==0.14.2 (from -r requirements.txt (line 2))
  Downloading requests-0.14.2.tar.gz (361kB)
    100% |████████████████████████████████| 368kB 877kB/s 
Collecting httplib2 (from prestapyt->-r requirements.txt (line 1))
  Downloading httplib2-0.9.2.zip (210kB)
    100% |████████████████████████████████| 215kB 708kB/s 
Building wheels for collected packages: requests, httplib2
  Running setup.py bdist_wheel for requests ... done
  Stored in directory: /home/odoo/.cache/pip/wheels/a7/d7/7b/e60ca9d7e24c3a102a2ffdaf27031ec9c3fcffdff3f1060de8
  Running setup.py bdist_wheel for httplib2 ... done
  Stored in directory: /home/odoo/.cache/pip/wheels/c7/67/60/e0be8ccfc1e08f8ff1f50d99ea5378e204580ea77b0169fb55
Successfully built requests httplib2
Installing collected packages: httplib2, requests, prestapyt
  Found existing installation: requests 2.10.0
    Uninstalling requests-2.10.0:
      Successfully uninstalled requests-2.10.0
  Running setup.py develop for prestapyt
Successfully installed httplib2-0.9.2 prestapyt requests-0.14.2
```

Restarted odoo server and log said:

```
2016-05-27 22:05:23,978 3002 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/home/odoo/odoo/lib/python2.7/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/odoo/odoo/lib/python2.7/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/openerp/service/server.py", line 291, in app
    return self.app(e, s)
  File "/opt/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/openerp/http.py", line 1292, in __call__
    self.load_addons()
  File "/opt/odoo/openerp/http.py", line 1313, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/opt/odoo/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/odoo/addons/calendar/__init__.py", line 22, in <module>
    from . import calendar
  File "/opt/odoo/addons/calendar/calendar.py", line 14, in <module>
    from dateutil import rrule
  File "/home/odoo/odoo/lib/python2.7/site-packages/dateutil/rrule.py", line 19, in <module>
    from six.moves import _thread
ImportError: cannot import name _thread
```

Resulting in an error 500... Refreshing browser (chrome in Ubuntu 14.04 LTS), log not changes but in the browser:

```
Could not get content for /web/static/lib/cleditor/jquery.cleditor.css defined in bundle 'web.assets_backend'.
Could not get content for /web/static/lib/jquery.textext/jquery.textext.css defined in bundle 'web.assets_backend'.
Could not get content for /web/static/lib/select2/select2.css defined in bundle 'web.assets_backend'.
Could not get content for /web/static/lib/bootstrap/css/bootstrap.css defined in bundle 'web.assets_backend'.
Could not get content for /web/static/lib/jquery.ui.bootstrap/css/custom-theme/jquery-ui-1.9.0.custom.css defined in bundle 'web.assets_backend'.
Could not get content for /web/static/lib/jquery.ui.timepicker/css/jquery-ui-timepicker-addon.css defined in bundle 'web.assets_backend'.
Could not get content for /web/static/lib/jquery.ui.notify/css/ui.notify.css defined in bundle 'web.assets_backend'.
Could not get content for /web/static/src/css/base.css defined in bundle 'web.assets_backend'.
Could not get content for /web/static/src/css/data_export.css defined in bundle 'web.assets_backend'.
Could not get content for /base/static/src/css/modules.css defined in bundle 'web.assets_backend'.
Could not get content for /im_chat/static/src/css/im_common.css defined in bundle 'web.assets_backend'.
Could not get content for /im_chat/static/src/css/im_chat.css defined in bundle 'web.assets_backend'.
Could not get content for /web_calendar/static/src/css/web_fullcalendar.css defined in bundle 'web.assets_backend'.
Could not get content for /web_calendar/static/lib/fullcalendar/css/fullcalendar.css defined in bundle 'web.assets_backend'.
Could not get content for /web_diagram/static/src/css/base_diagram.css defined in bundle 'web.assets_backend'
Could not get content for /web_gantt/static/src/css/gantt.css defined in bundle 'web.assets_backend'.
Could not get content for /web_gantt/static/lib/dhtmlxGantt/codebase/dhtmlxgantt.css defined in bundle 'web.assets_backend'.
Could not get content for /web_graph/static/src/css/graph.css defined in bundle 'web.assets_backend'.
Could not get content for /web_graph/static/src/css/nv.d3.css defined in bundle 'web.assets_backend'.
Could not get content for /web_kanban/static/src/css/kanban.css defined in bundle 'web.assets_backend'.
Could not get content for /web_tests/static/src/css/web_tests.css defined in bundle 'web.assets_backend'.
Could not get content for /web_view_editor/static/src/css/view_editor.css defined in bundle 'web.assets_backend'.
```

And unformated bullet item "Settings", the Odoo logo, "Edit Company Data" and "powered by Odoo" legend... Nothing else...

Before writte these lines I check twice this behavior (thanks to use a Virtual Box) and checked owner, group and permissions... Nothing changed because they are correct...

How can I get Odoo and your connector working?

Thanks in advance...

**Comment by pedrobaeza** [comment]
This is the repository for Prestashop connector, and thus this is not related, but also the issues are not for resolving questions, but for reporting problems on the code, what is not your case (but ignorance of the method to install Odoo), so I recommend you to post the question on Odoo forums or mailing lists. Someone maybe can help with that.

**Comment by DGEAPerez** [comment]
@pedrobaeza I know I'm "ignorant" in this "new" stuff (for me)... But I can suspect you didn't read the part where I wrotte :"Then tryed to follow **your guide**, and using the akretyon prestapyt or **running the pip for requirements from your sources**, results in Odoo stops works..."

AFIK, if I use your code, is your bussiness... I'm sorry if this is "rude", it's very frustrant when you only found "no answer" every where...

Thanks... :)

**Comment by pedrobaeza** [comment]
It's not my code, it's only a problem of scope. This is not intended for what you want. Try where I have said (forums or mailing lists), and give more information at least (Odoo/OpenERP version, full steps...)

**Comment by DGEAPerez** [comment]
@pedrobaeza I know it's not your code, else "yours".. But this it's a detail... I explained to you, by PM, how I reached here...
About more "information" all is in the first message:

The full steps I followed to install are here
https://odootricks.wordpress.com/2014/09/30/installing-odoo-8-on-centos-6-with-virtual-python-install/
Where you can read I'm talking about Odoo 8 in a CentOS 6 (and I pointed I'm using a 6.7 in a virtual box)

Again, all is working until I run from your readme:

```
pip install -r requirements.txt
```

Then Odoo broken as I detailed... Thanks again...

**Comment by pedrobaeza** [comment]
connector-prestashop (which is not my code) is not migrated to odoo v8, as you can see in the README in the section "Unported addons", so there's no possibility that this works.

**Comment by alexis-via** [comment]
For archives: the error may come from the version of the lib "requests". You should have:

```
# pip freeze|grep requests
requests==2.9.1
```

If you have version 0.14.2, you get this error.

**Comment by alexis-via** [comment]
In fact, it is the installation of prestapyt which brings requests 0.14.2, but it has been fixed last month in this commit https://github.com/akretion/prestapyt/commit/c04f56ea32b2a59cd34321e9f04bef8281be6c75
