### ISSUE TITLE
Odoo 9 installation problem

### ISSUE THREAD

**Issue by hamhc** [OCA/connector-prestashop#21]
Hi, everyone.

I've followed all the steps found on odoo tutorials about how to install third party modules on odoo, but I haven't been able to see this addon on my app list.. Does this connector work with odoo 9?.

Thanks a lot for your answer.

**Comment by flotho** [comment]
Hi,
The connector is not yet ported to v9. Major evolutions have been inserted in odoo core from v8 to v9 so that the community have to migrate many module to deal with all of this.
You'll have to either be patient or participate.

regards

**Comment by hamhc** [comment]
Thanks a lot for you answer @flotho. Greetings!
