### ISSUE TITLE
How to call alter context from a @prestashop class

### ISSUE THREAD

**Issue by flotho** [OCA/connector-prestashop#26]
Hi,

@pedrobaeza , @guewen I'm about to deliver the product matching on a PR https://github.com/guewen/connector-prestashop/pull/3
Yet as the product.product are not created but written, I have a problem with the _check_default_on method
I would like to alter the context here : https://github.com/guewen/connector-prestashop/pull/3/files#diff-2dc84c07ca9ac7470689ffd6c16c3402R71
How can it be passed/altered from a @prestashop class ?

**Comment by guewen** [comment]
like anywhere else with odoo: `self.env['product.product'].with_context(xxx=value).search([])`

**Comment by flotho** [comment]
@guewen ,
I think my question is not written in a comprehensible way. 
I want to set the context if a value of the PSbackend is set, so if I'm right, getting the current backend is only possible in Prestashop class, that is why I was trying to set the context in the importer.py of the product.template.
Yet the with_context couldn't be applied to the self of a Prestashop class. I particulary want to set it there https://github.com/guewen/connector-prestashop/blob/9.0-migration-connector-prestashop/connector_prestashop/models/product_template/importer.py#L379 so that it will be available https://github.com/guewen/connector-prestashop/pull/3/files#diff-2dc84c07ca9ac7470689ffd6c16c3402R71
How is it possible?
Regards

**Comment by pedrobaeza** [comment]
I think you need to rely on other technique different from the context for that.
