### ISSUE TITLE
Who is using this connector

### ISSUE THREAD

**Issue by mcassuto** [OCA/connector-prestashop#28]
Hello,

We really want to use Odoo with Prestashop.
How robust is the connector ? Is there production environments using it ?
Could we have some references ? 

Thanks a lot,
Marc

**Comment by omalbastin** [comment]
Hi, We are using the prestashop odoo connector for our customer and its in production. By using this module as a reference we had to create the functionality from scratch

**Comment by mcassuto** [comment]
Hello @omalbastin , what do you mean by " we had to create the functionality from scratch" ?

**Comment by pedrobaeza** [comment]
Closing as outdated. See current PRs for working connectors.
