### ISSUE TITLE
Transport product comes with 0 quantity

### ISSUE THREAD

**Issue by mcassuto** [OCA/connector-prestashop#31]
**How to reproduce**
* create an order in prestashop; this order must include a shipping fee
* synch the orders

=> in Odoo, the newly created sale_order contains the correct number of lines including the shipping product.
BUT the quantity for the shipment is set to 0 which leads to a wrong sale_order price.

**Comment by pedrobaeza** [comment]
Please don't open more issues for a module that is not yet merged. Write them on the opened PR.
