### ISSUE TITLE
Anyone could install this module in Windows?

### ISSUE THREAD

**Issue by weixinxu1233** [OCA/connector-prestashop#35]
Hello,

I'm using Odoo 9 in Windows, i can upload modules (move on Addons folder).

But when i'm trying install modules, failed because dependencies ... 

 You try to install module 'prestashoperpconnect' that depends on module 'product_images'.
But the latter module is not available in your system.

Someone know? Thanks

**Comment by pedrobaeza** [comment]
The module is not installable in Odoo 9 without the PRs that are currently being developed. You need to know how to download and apply them, which is out of the scope of this issue.

**Comment by weixinxu1233** [comment]
Thank you, so maybe i could install this module in Linux?

**Comment by pedrobaeza** [comment]
I think you can install in both (although Linux is the preferred platform), but you need to extract the dependencies from GitHub PRs.

**Comment by weixinxu1233** [comment]
What does extract the dependencies from GitHub PRs means ... ? Sorry, i'm beginner in github, i was looking information but i could not found

**Comment by pedrobaeza** [comment]
Again, this is out of the scope of this issue. PR is pull request, and extract is that you get the code from there, not from the main branch.

**Comment by weixinxu1233** [comment]
Thank you
