### ISSUE TITLE
Reduce number of connections for http requests on PrestaShop

### ISSUE THREAD

**Issue by guewen** [OCA/connector-prestashop#37]
A simple import of a product issues a huge number of http requests to retrieve all the necessary data.
We could probably reduce the number of requests by grouping some reads (like reading options in one request). We should also use a `requests.Session` that is opened only once for the duration of an import/export. The session could be stored in the `ConnectorEnvironment` and propagated to `prestapyt` (https://github.com/prestapyt/prestapyt/blob/master/prestapyt/prestapyt.py#L70).

**Comment by pedrobaeza** [comment]
:+1: good idea
