### ISSUE TITLE
data import with "since" information locks into an unfinished state with error

### ISSUE THREAD

**Issue by bodi000** [OCA/connector-prestashop#40]
Hi there,
I try to use the v7 connector.
While the first import works correctly (the product attributes do not come, though) a second one, once the field xxx-since is filled with a date, blocks the whole process.

e.g.:  Prepare the import of orders modified on Prestashop , 
task openerp.addons.prestashoperpconnect.unit.import_synchronizer.import_orders_since(1, datetime.datetime(2017, 3, 30, 1, 45, 20, tzinfo=<DstTzInfo 'Europe/Zurich' CEST+2:00:00 DST>))

produces after a short moment, while remaining in the "waiting" state, the following traceback if I want to queue it or terminate.

Server Traceback (most recent call last):
  File "/opt/openerp/7.0/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/home/bstanciu/workspace/odoo-7.0/openerp/netsvc.py", line 306, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/home/bstanciu/workspace/odoo-7.0/openerp/service/web_services.py", line 632, in dispatch
    res = fn(db, uid, *params)
  File "/home/bstanciu/workspace/odoo-7.0/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, **kw or {})
  File "/home/bstanciu/workspace/odoo-7.0/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, *args, **kwargs)
  File "/home/bstanciu/workspace/odoo-7.0/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, *args, **kw)
  File "/home/bstanciu/workspace/odoo-7.0/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/opt/openerp/7.0/extra-addons/connector/queue/model.py", line 180, in button_done
    result=result, context=context)
  File "/opt/openerp/7.0/extra-addons/connector/queue/model.py", line 167, in _change_job_state
    job = storage.load(job.uuid)
  File "/opt/openerp/7.0/extra-addons/connector/queue/job.py", line 292, in load
    func = _unpickle(stored.func)
  File "/opt/openerp/7.0/extra-addons/connector/queue/job.py", line 115, in _unpickle
    raise NotReadableJobError('Could not unpickle.', pickled)
NotReadableJobError: ('Could not unpickle.', "(S'openerp.addons.prestashoperpconnect.unit.import_synchronizer.import_orders_since'\np1\n(I1\ncdatetime\ndatetime\np2\n(S'\\x07\\xe1\\x03\\x1e\\x01-\\x14\\x00\\x00\\x00'\ncpytz\n_p\np3\n(S'Europe/Zurich'\np4\nI7200\nI3600\nS'CEST'\np5\ntRp6\ntRp7\ntp8\n(dp9\nt.")

thank you for any insight, I cannot get it going..
B

**Comment by pedrobaeza** [comment]
I'm afraid that version in barely unsupported, and it's very old, but let's see if someone answers.

**Comment by bodi000** [comment]
I can understand that, and thank you for your quick reaction. However, I think that the code closely involved is quite the same up to the latest versions. 

BTW, I tried to install v10 to compare, but I cannot even get the modules into the list to install... I know this is not proper to connectors, but is there any trick to get additional modules into the list, without changing the 'installable' parameter (in manifest) into True?

**Comment by pedrobaeza** [comment]
No, the code is totally different, because migrated versions are not merged. See https://github.com/OCA/connector-prestashop/pull/22 and https://github.com/OCA/connector-prestashop/pull/34.

8.0 version is also half-abandoned, and we are focused on version 9.

**Comment by bodi000** [comment]
Pedro,
Thank you very much for your feedback. I have systems running on 7 or even 6.1. not so easy to upgrade... I will try v9 and hopefully learn from differences :-)

Now, which would be a working v9 branch, please? 

kind regards,
Bogdan

**Comment by pedrobaeza** [comment]
This one is fully functional: https://github.com/OCA/connector-prestashop/pull/34
