### ISSUE TITLE
Impossible instalation

### ISSUE THREAD

**Issue by antoniomperez** [OCA/connector-prestashop#48]
Hi,

I am trying to install the connector-prestashop and it is imposible.

If I copy al files in adding directory, when I update all my app in odoo, it doesn´t detect modules.

I have followed all steps and I can´t find the solution.

I have used the setup.py and I have some errors, using the command "python setup.py install" like followings:
<img width="706" alt="captura de pantalla 2017-04-19 a las 17 28 47" src="https://cloud.githubusercontent.com/assets/12720652/25188242/b1b3adb4-2525-11e7-9db1-558d5ead39d4.png">

I have odoo 10 and python 2.7.
pip 9.1
setup tools-odoo
setup tools 35.0

anyone can help?

**Comment by pedrobaeza** [comment]
Normal, as the connector is not migrated to v10.

**Comment by antoniomperez** [comment]
so, why is there branch 10.0?

**Comment by pedrobaeza** [comment]
For hosting the migration when it's done.
