### ISSUE TITLE
Adding connector prestashop to Odoo v9

### ISSUE THREAD

**Issue by Razgort** [OCA/connector-prestashop#52]
Hi,

I'm integrated Odoo connector prestashop in my Odoo 9 OCB version.
The connector is installed. But when i want to make a sale on odoo, i get a lot of errors like these bellow

I installed the connector based on the configuration of guewen : https://github.com/guewen/odoo-prestashop-dev

![screen shot 05-17-17 at 08 22 am](https://cloud.githubusercontent.com/assets/9212658/26141110/88d866a8-3ada-11e7-9e74-4fd513e155a1.PNG)

this error comes repeatedly when i start my odoo with the connector.

![screen shot 05-16-17 at 05 07 pm](https://cloud.githubusercontent.com/assets/9212658/26141116/926b5784-3ada-11e7-9605-a4afe0d7e2c7.PNG)
![screen shot 05-16-17 at 12 26 pm](https://cloud.githubusercontent.com/assets/9212658/26141176/d3c18ffa-3ada-11e7-8884-39590ead6f97.PNG)
![screen shot 05-16-17 at 04 14 pm](https://cloud.githubusercontent.com/assets/9212658/26141189/e060511a-3ada-11e7-90be-e127648e6e76.PNG)

![screen shot 05-17-17 at 08 31 am](https://cloud.githubusercontent.com/assets/9212658/26141248/3531a1c6-3adb-11e7-9c84-402d5b1860b3.PNG)

Could someone plz be of any help about these errors ? Or already encounter errors like that ?

Thx in advance !
Best Regards !
Razgort

**Comment by pedrobaeza** [comment]
Next time, please pass only text with the trace, not screens.

Any clue, @simahawk or @sergio-teruel ?

**Comment by Razgort** [comment]
Ho, sry i'll do that next time but i screened when i was debugging yesterday ><

**Comment by sergio-teruel** [comment]
@pedrobaeza @Razgort   Mhhuuuu I'm watching errors not relative to connector module... 
First fix this errors and then try again.
You must use 9.0 branch not dev branchs..
Are you sure that all necessary branches are in 9.0?? p.g. e-commerce??

**Comment by pedrobaeza** [comment]
OK, then it's unrelated to connector itself.

**Comment by Razgort** [comment]
I'm using 9.0 branch actually ... 
i cloned this repository https://github.com/OCA/OCB.git with -b 9.0
and for the connector, i'm using this

[submodule "odoo/external-src/connector-prestashop"]
	path = odoo/external-src/connector-prestashop
	url = git@github.com:guewen/connector-prestashop.git
[submodule "odoo/external-src/connector-ecommerce"]
	path = odoo/external-src/connector-ecommerce
	url = git@github.com:OCA/connector-ecommerce.git
[submodule "odoo/external-src/connector"]
	path = odoo/external-src/connector
	url = git@github.com:OCA/connector.git
[submodule "odoo/external-src/bank-payment"]
	path = odoo/external-src/bank-payment
	url = git@github.com:OCA/bank-payment.git
[submodule "odoo/external-src/product-attribute"]
	path = odoo/external-src/product-attribute
	url = git@github.com:camptocamp/product-attribute.git
[submodule "odoo/external-src/sale-workflow"]
	path = odoo/external-src/sale-workflow
	url = git@github.com:OCA/sale-workflow.git
[submodule "odoo/external-src/product-variant"]
	path = odoo/external-src/product-variant
	url = git@github.com:camptocamp/product-variant.git
[submodule "odoo/external-src/server-tools"]
	path = odoo/external-src/server-tools
	url = git@github.com:OCA/server-tools.git

**Comment by Razgort** [comment]
So i recloned all repository from OCA with branch 9.0 and here is my git module
[submodule "Modules-OCA/reporting-engine"]
	path = Modules-OCA/reporting-engine
	url = https://github.com/OCA/reporting-engine
[submodule "Modules-OCA/management-system"]
	path = Modules-OCA/management-system
	url = https://github.com/OCA/management-system
[submodule "Modules-OCA/knowledge"]
	path = Modules-OCA/knowledge
	url = https://github.com/OCA/knowledge
[submodule "Modules-OCA/account-fiscal-rule"]
	path = Modules-OCA/account-fiscal-rule
	url = https://github.com/OCA/account-fiscal-rule
[submodule "Modules-OCA/account-financial-tools"]
	path = Modules-OCA/account-financial-tools
	url = https://github.com/OCA/account-financial-tools
[submodule "Modules-OCA/account-financial-reporting"]
	path = Modules-OCA/account-financial-reporting
	url = https://github.com/OCA/account-financial-reporting
[submodule "Modules-Store/aeroo_reports"]
	path = Modules-Store/aeroo_reports
	url = https://github.com/ingadhoc/aeroo_reports.git
[submodule "Modules-Store/multi-store"]
	path = Modules-Store/multi-store
	url = https://github.com/ingadhoc/multi-store
[submodule "Modules-OCA/connector-presta-deps/server-tools"]
	path = Modules-OCA/connector-presta-deps/server-tools
	url = https://github.com/OCA/server-tools.git
[submodule "Modules-OCA/connector-presta-deps/sale-workflow"]
	path = Modules-OCA/connector-presta-deps/sale-workflow
	url = https://github.com/OCA/sale-workflow.git
[submodule "Modules-OCA/connector-presta-deps/product-variant"]
	path = Modules-OCA/connector-presta-deps/product-variant
	url = https://github.com/OCA/product-variant.git
[submodule "Modules-OCA/connector-presta-deps/product-attribute"]
	path = Modules-OCA/connector-presta-deps/product-attribute
	url = https://github.com/OCA/product-attribute.git
[submodule "Modules-OCA/connector-presta-deps/connector-prestashop"]
	path = Modules-OCA/connector-presta-deps/connector-prestashop
	url = https://github.com/OCA/connector-prestashop.git
[submodule "Modules-OCA/connector-presta-deps/connector-ecommerce"]
	path = Modules-OCA/connector-presta-deps/connector-ecommerce
	url = https://github.com/OCA/connector-ecommerce.git
[submodule "Modules-OCA/connector-presta-deps/bank-payment"]
	path = Modules-OCA/connector-presta-deps/bank-payment
	url = https://github.com/OCA/bank-payment.git
[submodule "Modules-OCA/connector-presta-deps/connector"]
	path = Modules-OCA/connector-presta-deps/connector
	url = https://github.com/OCA/connector.git

**Comment by simahawk** [comment]
@Razgort Sergio and Pedro are right: you must avoid collecting tons of error in one ticket, especially if they are not strictly related to the current repo or module. Plus, please, copy paste traceback from the shell, not with screenshots.

1st thing 1st: make sure you have latest version of everything. In this regard DO NOT rely on https://github.com/guewen/odoo-prestashop-dev which is now outdated as is just for personal and skilled dev usage and is not yet up to date with all the work that has been done.

And be careful w/ submodule: it can bite you as is not guaranteed that it switches to correct branch when you checkout.

**Comment by Razgort** [comment]
Hi sima,
This mornign i repulled all repository for the prestashop connector on the last version of the 9.0 branch from OCA repository and i still have issues

My main issue is actually this one : 
![image](https://cloud.githubusercontent.com/assets/9212658/26150563/2f542b74-3aff-11e7-978c-e03c6c17a222.png)

The error occurs each time i want to confirm a sale ....

**Comment by simahawk** [comment]
we cannot determine anything from this:  STOP posting images instead of full traceback.

**Comment by Razgort** [comment]
Sry the traceback is as follow : 

> 2017-05-17 12:52:44,193 2152 ERROR cop-empty openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "G:\OCB-9.0\openerp\http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "G:\OCB-9.0\openerp\http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "G:\OCB-9.0\openerp\http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "G:\OCB-9.0\openerp\service\model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "G:\OCB-9.0\openerp\http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "G:\OCB-9.0\openerp\http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "G:\OCB-9.0\openerp\http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "G:\OCB-9.0\addons\web\controllers\main.py", line 900, in call_button
    action = self._call_kw(model, method, args, {})
  File "G:\OCB-9.0\addons\web\controllers\main.py", line 888, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "G:\OCB-9.0\openerp\api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "G:\OCB-9.0\openerp\api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "G:\OCB-9.0\addons\delivery\models\sale_order.py", line 35, in action_confirm
    res = super(SaleOrder, self).action_confirm()
  File "G:\OCB-9.0\openerp\api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "G:\Odoo-Source\Modules-OCA\connector-presta-deps\sale-workflow\sale_exception\models\sale.py", line 113, in action_confirm
    return super(SaleOrder, self).action_confirm()
  File "G:\OCB-9.0\openerp\api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "G:\OCB-9.0\addons\sale\sale.py", line 425, in action_confirm
    order.order_line._action_procurement_create()
  File "G:\OCB-9.0\openerp\api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "G:\OCB-9.0\addons\procurement_jit\sale.py", line 11, in _action_procurement_create
    res = super(SaleOrderLine, self)._action_procurement_create()
  File "G:\OCB-9.0\openerp\api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "G:\OCB-9.0\addons\sale\sale.py", line 601, in _action_procurement_create
    new_procs.run()
  File "G:\OCB-9.0\openerp\api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "G:\OCB-9.0\openerp\api.py", line 574, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "G:\OCB-9.0\addons\stock\procurement.py", line 334, in run
    self.pool.get('stock.move').action_confirm(cr, uid, move_to_confirm_ids, context=context)
  File "G:\OCB-9.0\openerp\api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "G:\OCB-9.0\openerp\api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "G:\OCB-9.0\addons\delivery\models\stock_move.py", line 34, in action_confirm
    res = super(StockMove, self).action_confirm()
  File "G:\OCB-9.0\openerp\api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "G:\OCB-9.0\openerp\api.py", line 574, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "G:\OCB-9.0\addons\stock\stock.py", line 2383, in action_confirm
    self._picking_assign(cr, uid, move_ids, context=context)
  File "G:\OCB-9.0\openerp\api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
TypeError: _picking_assign() takes at least 7 arguments (5 given)

**Comment by pedrobaeza** [comment]
Definitively nothing to do with the connector. Any module you have put overwrites the method `_picking_assign`, and raises when using the connector.

**Comment by Razgort** [comment]
for me it's a dependency of the connector at this line

File "G:\Odoo-Source\Modules-OCA\connector-presta-deps\sale-workflow\sale_exception\models\sale.py", line 113, in action_confirm
return super(SaleOrder, self).action_confirm()

**Comment by simahawk** [comment]
No, it has nothing to do w/ the connector. Judging from the error there's some module that is is not passing all the arguments to the old style api in _picking_assign call.

**Comment by Razgort** [comment]
I think your are right but i'm stuck on this for the moment. I don't find from which one it comes =(
