### ISSUE TITLE
html2text

### ISSUE THREAD

**Issue by dstemple67** [OCA/connector-prestashop#59]
Receiving this error when installing in Odoo 9.

Unable to install module "connector_prestashop" because an external dependency is not met: No module named html2text

The only place I see html2text is in the mail module

![odooconnector](https://cloud.githubusercontent.com/assets/29187649/26766909/0d9c50d4-4968-11e7-83d9-75abab9c8264.JPG)

**Comment by pedrobaeza** [comment]
Install that Python library.
