### ISSUE TITLE
Job Runner

### ISSUE THREAD

**Issue by dstemple67** [OCA/connector-prestashop#61]
Hello all,

This is a great connector but I'm having trouble with the jobs. I've tried changing the dates for importing as well as leaving them blank.

The metadata import went fine as did the base but I'm not getting any of the orders or customers imported. When checking the connection, it is successful. I read through the Job Runner documentation and saw this tip "Alternatively, if you are not able to activate it, you can enable the scheduled job called "Enqueue Jobs" - I don't see this as an option in the connector. I'm sure I'm missing something simple.

No errors in the Odoo log.

Any assistance is greatly appreciated.

Thanks!

**Comment by pedrobaeza** [comment]
Sorry, this is not an issue of PrestaShop connector itself, so I close here. Ask on the forums or mailing lists for assistance.
