### ISSUE TITLE
No module named VCR

### ISSUE THREAD

**Issue by abennani15** [OCA/connector-prestashop#67]
When installing on odoo 9 i get 'No module named vcr'
with pip freeze : 
...
vcr==0.0.9
vcrpy==1.11.1
...
Using python 2.7
What's the issue ? 
Thanks

**Comment by pedrobaeza** [comment]
This should be something with your installation/environment/deploy. Check possible virtualenv. But it's not a problem in the module itself.

**Comment by abennani15** [comment]
Hello,
i've been testing the module on another server with odoo 9 but still getting the "no module named VCR" error
Can you please send me versions and/or link to the correct vcr to check ? using python 2.7
Thanks

**Comment by pedrobaeza** [comment]
Sorry, but the pip version works, so check again your environment.

**Comment by abennani15** [comment]
with pip freeze i get : 
vcr==0.0.9
vcrpy==1.10.2
using odoo 9, python 2.7 / Debian GNU/Linux 7.10
it must be installed on an alternative path ? other than /usr/local/lib/python2.7/dist-packages/vcr
Thanks again

**Comment by pedrobaeza** [comment]
Again, that's something on your deployment. Nothing to be fixed here.
