### ISSUE TITLE
Migrate Prestashop connector to v8

### ISSUE THREAD

**Issue by percevaq** [OCA/connector-prestashop#7]
This issue is intended to collect all the information about the migration to v8 of the prestashop connector.

@pedrobaeza and I are starting to work on this migration already. If anyone more want to collaborate, please comment here.

Any tip or question that we should take into account?

@legalsylvain, I'm seeing that you have a 7.0 refactorization as a PR. Does it worth to use it as base?

**Comment by sebastienbeau** [comment]
Hi we have 2 customers interested by prestashop connector on v8 version, we will start to work on it in January. But I think we will need help. This connector still not have the same quality as the magento one (we didn't do any funding on it).
It will be great if we can do some clean and integrate a maximun of unit testing. The best way to sucess in having a such great connector will to have a maximun of contribution in code or money. (I prefers code, because it's increase the number of contributor).

Who is interessed in contributing?
Some of you are interrested by doing a code sprint on the connector? (we can do a remote and physical code sprint)

**Comment by pedrobaeza** [comment]
Hi, Sebastien, good to know it.

We are in a hurry, because we need a working v8 environment with the connector to the end of this year, so we are going to start with a migration as is, repairing bugs, and changing the use of product attributes from community to the core attributes of v8. If you think we can make a code sprint very soon (next week, or at maximum, the other one), we can put 2 resources (me and Joaquin) on that task.

**Comment by sebastienbeau** [comment]
Hi Pedro, I will see if we can work on it before, but our planning is already really full for the next week.
Just to know for the catalog do you plan to manage it from Odoo and then export it in Prestashop? Or do you will manage the catalog in Prestashop and then import it in Odoo? If you plan to manage the catalog from Odoo, do you need to support the variant?

Thanks

**Comment by pedrobaeza** [comment]
The idea is to change the catalog to support new v8 variants, but initially not to export Odoo > Prestashop. Only Prestashop > Odoo. In a second phase on 2015, we want to do it the contrary also.

**Comment by sebastienbeau** [comment]
Hi Pedro, really sorry for the delay (crazy planning here). Unlucky we will be not able to work on the prestashop connector before end of January.
We will try to do our best to review all of your merge proposal (do not hesitate to send us a private mail to review your code as soon as possible).
Regarding the catalog management I think it's a good idea to do it in two step. Indeed exporting product from Odoo to Prestashop will need more extra work, and it's better to focus on other more strategical point.
For managing the variant the actual version have a really simple way to support it (the customer had a restricted budget so this was better than nothing), basically each combinaison of prestashop was imported as a simple product in Odoo (a link was stored between the combinaison and the main product). This should be totaly refactored as we can use the native variant of Odoo 8 and directly import product combinaison as variant.

If you need a simple setup of prestashop you can use the vagrant recipe here https://github.com/akretion/ak-prestashop (note : I hope that I will have the time soon to propose a alternative using docker)

If you have any question, do not hesitate to contact me, I will try to do my best to be available.
Ademas hablo espanol y no tengo muchas opportunidades de practicarlo ;)

**Comment by sebastienbeau** [comment]
Regarding the PR of Sylvain, I think it's worth using it. I will see with him if we can merge it this weekend (I just send him an email).

**Comment by kintaro1981** [comment]
Hi and thank you for this connector.
Are there any news about support to v8?

**Comment by pedrobaeza** [comment]
We will make a PR tomorrow with the first version.

Regards.

**Comment by kintaro1981** [comment]
wow! thank you

**Comment by pedrobaeza** [comment]
We are refactoring one dependency module (product_images), but we are still working on it and we will get results soon. Stay tuned.

**Comment by JADCO5692** [comment]
When can we get the odoo prestashop v8 connector??

**Comment by kintaro1981** [comment]
In some months I'm going to migrate a Virtuemart shop to Prestashop and then make it multi-site and connecting it to odoo v8 (multi company). So if you need someone to test the connector I can give some feedback.

p.s. I'm newbie about odoo.

**Comment by beernaert** [comment]
I'm willing to help testing as well, I got prestashop 1.6.0.13 and odoo 8
Looking forward to help in this project.

**Comment by pedrobaeza** [comment]
I have made a PR for tracking the work in progress of the connector:

https://github.com/OCA/connector-prestashop/pull/11

**Comment by beernaert** [comment]
I will follow it. Looking forward for testing.

**Comment by jalzaga** [comment]
We need the Prestashop connector for a customer in v8 and if there is a possibility to collaborate in the testing we are willing to. Just let us know what is the latest version of code to test.

**Comment by pedrobaeza** [comment]
See https://github.com/OCA/connector-prestashop/pull/11 for the latest changes.

**Comment by flotho** [comment]
Hi @percevaq , @pedrobaeza,

I would like to help you on this, how can I do this?
regards

**Comment by NVD77** [comment]
What is the status of the migration to ODOO 8? How can we help?

**Comment by atchuthan** [comment]
What is the status of the migration to ODOO 8? 
We have 2 work in progress PR's for prestashoperpconnect: 
- https://github.com/OCA/connector-prestashop/pull/11 by @pedrobaeza 
- https://github.com/OCA/connector-prestashop/pull/16 by @parthivgls 

Could I have some insights on which PR to consider for migration?
