### ISSUE TITLE
job not start odoo not import from prestashop

### ISSUE THREAD

**Issue by Stefano7777777** [OCA/connector-prestashop#78]
i've installed odoo connector, i've imported tax and nothing.
There is a list of jobs but they do not leave
i'm in localhost, i'have to test all for install on-line
can anyone help me please?

**Comment by pedrobaeza** [comment]
That's because you have configured properly JobRunner or you are not launching enqueue cron job. See http://odoo-connector.com/guides/jobrunner.html

**Comment by Stefano7777777** [comment]
Sorry but i can not understand how to configure job runner i have read the instructions several times, is there a way to launch cron jobs manually?

**Comment by pedrobaeza** [comment]
There's a cron job called "Enqueue jobs" or similar.

**Comment by Stefano7777777** [comment]
Where can I find it? Because it is not in jobs or in settings

**Comment by pedrobaeza** [comment]
Sorry, but this is again something outside of the scope of this. I think you need more Odoo knowledge before starting to make this implementation by your own.

**Comment by Stefano7777777** [comment]
Thanks for the help, however, I found Enqueue Jobs, in Italian it has another denomination. Activated everything but it does not matter. Doing nothing will find a solution in another way.
Thanks anyway
