### ISSUE TITLE
Tutorial to install „connector”

### ISSUE THREAD

**Issue by georgedinamic** [OCA/connector-prestashop#8]
Developers and advanced users, please all, do a small tutorial with steps, how to..., where to... about „Prestashop OpenERP Connector”. Or, if somebody knows, where to found steps please let a link.
What i found on github and google search is not clear for newbies. I now to work with Debian command, but i hope to see a more explicit tutorial for this connector.
With best wishes and congratulations for your work, we start together in 2015!

**Comment by pedrobaeza** [comment]
See http://odoo-connector.com/

**Comment by witoszek** [comment]
Hello I can not understand these code 
     split_record = {}
        languages = self.find_each_language(record)
        if not languages:
            raise FailedJobError(
                _('No language mapping defined. '
                  'Run "Synchronize base data".')

In which site should I put the language in odoo in the configuration?

I have placed the language in all the odoo boxes where the language appears except in the backend because it does not admit it

**Comment by witoszek** [comment]
An ERP record with same ID already exists on PrestaShop.
