### ISSUE TITLE
Error Product Export from Odoo 9 to Prestashop 1.6

### ISSUE THREAD

**Issue by ghost** [OCA/connector-prestashop#88]
Hello, 

I'm currently having Problems with Prestashop Connector Add-On for Odoo Version 9.
The First Problem: Documentation for the Job Runner, with the Information in the Documentation it will not work, I found another Person who also had Problems getting it to run, the Answer to his Problem: one should follow strictly the Documentation. Well If you follow it, it will not work, the Addon queue_job dosent exist. 
**server_wide_modules= web,web_kanban,queue_job**. 

I only got the Job Runner working with **server_wide_modules= web,web_kanban,connector**. 

Now I have a Problem which needs attention: 
I can Import everything from Prestashop Version 1.6.1.2 to Odoo 9, Orders, Products and so forth. Works fine an fast.
Now I made some Changes to the Products and Pricing Information in Odoo, as soon as I save the changes, I get an error Message from the Job Runner. 

Error: 
 Export a record on PrestaShop
UUID
	65b7e007-c55a-429b-bf9b-6ca5ca2f004d
Aufgabe
	openerp.addons.connector_prestashop.unit.exporter.export_record('prestashop.product.template', 1, {u'list_price': 1299})
Job-Funktion
	openerp.addons.connector_prestashop.unit.exporter.export_record
Kanal
	root.prestashop
Priorität
	20
Ausführen nur nach
	
Benutzer-ID
	Administrator
	
Anlagedatum
	26.12.2017 23:07:57
Einreihungszeitpunkt
	26.12.2017 23:07:58
Start Datum
	26.12.2017 23:07:58
Erledigt am
	
Aktueller Versuch / Maximale Versuche 1 / 5 If the max. retries is 0, the number of retries is infinite.
Ausnahme Information
Traceback (most recent call last):
  File "/opt/odoo_addons/shop_connect/connector/controllers/main.py", line 90, in runjob
    self._try_perform_job(session_hdl, job)
  File "/opt/odoo_addons/shop_connect/connector/controllers/main.py", line 66, in _try_perform_job
    job.perform(session)
  File "/opt/odoo_addons/shop_connect/connector/queue/job.py", line 493, in perform
    self.result = self.func(session, *self.args, **self.kwargs)
  File "/opt/odoo_addons/shop_connect/connector_prestashop/unit/exporter.py", line 352, in export_record
    return exporter.run(binding_id, fields=fields, **kwargs)
  File "/opt/odoo_addons/shop_connect/connector_prestashop/unit/exporter.py", line 52, in run
    result = self._run(*args, **kwargs)
  File "/opt/odoo_addons/shop_connect/connector_prestashop/unit/exporter.py", line 292, in _run
    map_record = self._map_data()
  File "/opt/odoo_addons/shop_connect/connector_prestashop/unit/exporter.py", line 221, in _map_data
    return self.mapper.map_record(self.binding)
  File "/opt/odoo_addons/shop_connect/connector_prestashop/unit/exporter.py", line 322, in mapper
    TranslationPrestashopExportMapper)
  File "/opt/odoo_addons/shop_connect/connector/connector.py", line 312, in get_connector_unit
    self.model_name)(self)
  File "/opt/odoo_addons/shop_connect/connector/backend.py", line 274, in get_class
    (base_class, session, model_name, matching_classes))
AssertionError: Several classes found for <class 'openerp.addons.connector_prestashop.unit.mapper.TranslationPrestashopExportMapper'> with session <Session db_name: hk, uid: 1, context: {'job_uuid': u'65b7e007-c55a-429b-bf9b-6ca5ca2f004d'}>, model name: prestashop.product.template. Found: set([<class 'openerp.addons.connector_prestashop_catalog_manager.models.product_template.exporter.ProductTemplateExportMapper'>, <class 'openerp.addons.connector_prestashop_manufacturer.models.product_template.exporter.ProductTemplateExportMapper'>])

Second thing I found, the Product Images dont get Imported or Exported from an to Odoo. 

The following of the descibed Functions don't Work:
    Create/modify attributtes and values in Odoo and push then in PrestaShop.
    Create/modify products and push them in PrestaShop.
    Create/modify products variants and push them in PrestaShop (combinations).
    Create/modify category and push them in PrestaShop.
    Create/modify image and push then in PrestaShop.

Thanks for all the Help.

**Comment by tetageek** [comment]
Hi, i have same problem, odoo 9 with install of prestashop_catalog_manager and same bug.

**Comment by ghost** [comment]
Hi, thanks for the Only One who wrote back. 

ok, so it can be reproduced. I think the development People schould read this. 

Since there has been no Reaction from anyone in this forum, I have decided not to go down this road and develop a new Software for these guys. The Connector ist way to buggy to be used even with good intention. 

I bought one from a Company, https://webkul.com. They have a working Sync in both Directions Odoo to Prestashop and Prestashop back to Odoo. And they also have Support for their development and can Fix any Issue there is. It only Cost 179,00 Euros. Thats the difference with real Software developers, they can take money for their Work. 

I will have to Advertise that no one should waste their Time with this Connector, it requires a lot more development, since Odoo Version 11 ist out and this buggy Software still only Supports Version 9, there is no need for anyone to try and fix these Issues. You would have to reprogramm everything in this Code, and thats not the Idea behind this. 

If anyone of theses so called developers still sees this Post, then Please do us all a favor. Delete this Crap from the Repository and write the issues into the Documentation. 

Even the Documentation is crap! 

And one thing I have found out about these People behind this Software. They havent fixed any Issue that has been posted here, I only read that the problem is on your side.

So Happy New Year to all and Hopefully no one has wasted their time an effort with this Shit Piece of Code disaster.

**Comment by ghost** [comment]
And this what I meant, they just close the Case without any type of Response, was my Response to Real for you guys??

Pedro: take some time to rethink your aproach to Problems and you might just geahead a little better. Plus your People skills could use a Fix. 

Please People buy the Products that cost Money, those products work without bug testing from Users!!!

**Comment by joserprieto** [comment]
If you don't know how to configure the addon, please, don't disturb.

Connector works.

Only in some particular situations the behaviour isn't the expected  (and you have a sample for dealing with this "connector_prestashop_customize_example").

Regards.

**Comment by tetageek** [comment]
I have same error when i want to export my product. So where is the configuration problem to resolve this ? 
I have read the doc to install this but i'm export my product 

AssertionError: Several classes found for <class 'openerp.addons.connector_prestashop.unit.mapper.TranslationPrestashopExportMapper'> with session <Session db_name: db_prod, uid: 7, context: {'job_uuid': u'82163459-e1d4-473b-b48b-bc2531178c94'}>, model name: prestashop.product.template. Found: set([<class 'openerp.addons.connector_prestashop_catalog_manager.models.product_template.exporter.ManufacturerExportMapper'>, <class 'openerp.addons.connector_prestashop_catalog_manager.models.product_template.exporter.ProductTemplateExportMapper'>])
 
Thanks a lot.
