### ISSUE TITLE
Export product record on PrestaShop 

### ISSUE THREAD

**Issue by tetageek** [OCA/connector-prestashop#90]
Hi, i'm sorry about this, but i'have problem when export product. 
Your module is ok when i want to synchronize prestashop > odoo but in other odoo > prestashop it's not ok on product. 
Perhaps i have missed configuration. 

Traceback (most recent call last):
  File "/odoo/custom/addons/connector/controllers/main.py", line 90, in runjob
    self._try_perform_job(session_hdl, job)
  File "/odoo/custom/addons/connector/controllers/main.py", line 66, in _try_perform_job
    job.perform(session)
  File "/odoo/custom/addons/connector/queue/job.py", line 493, in perform
    self.result = self.func(session, *self.args, **self.kwargs)
  File "/odoo/custom/addons/connector_prestashop/unit/exporter.py", line 352, in export_record
    return exporter.run(binding_id, fields=fields, **kwargs)
  File "/odoo/custom/addons/connector_prestashop/unit/exporter.py", line 52, in run
    result = self._run(*args, **kwargs)
  File "/odoo/custom/addons/connector_prestashop/unit/exporter.py", line 292, in _run
    map_record = self._map_data()
  File "/odoo/custom/addons/connector_prestashop/unit/exporter.py", line 221, in _map_data
    return self.mapper.map_record(self.binding)
  File "/odoo/custom/addons/connector_prestashop/unit/exporter.py", line 322, in mapper
    TranslationPrestashopExportMapper)
  File "/odoo/custom/addons/connector/connector.py", line 312, in get_connector_unit
    self.model_name)(self)
  File "/odoo/custom/addons/connector/backend.py", line 274, in get_class
    (base_class, session, model_name, matching_classes))
AssertionError: Several classes found for <class 'openerp.addons.connector_prestashop.unit.mapper.TranslationPrestashopExportMapper'> with session <Session db_name: db_prod, uid: 7, context: {'job_uuid': u'0e6fd3d8-d852-444a-8d11-ce8270249d05'}>, model name: prestashop.product.template. Found: set([<class 'openerp.addons.connector_prestashop_catalog_manager.models.product_template.exporter.ProductTemplateExportMapper'>, <class 'openerp.addons.connector_prestashop_catalog_manager.models.product_template.exporter.ManufacturerExportMapper'>])

**Comment by Knut2001** [comment]
Hello everybody,

First I wanted to thank you for the great module and the great work that is being done here.

I have the same issue as described above. I also suspect that it is some erroneous Konfigration, since it is not a general problem.

If someone can give a hint where we can search for the issue, I would be very grateful.

Thanks in advance.

**Comment by flotho** [comment]
Hi @tetageek , @Knut2001 ,
Could you precise the versions of Odoo /  Connector / Prestashop connector etc...
It would be easier to help you

**Comment by smkerz** [comment]
Hello, first of all thank you so much for developping this module which I use frequently.

I also have this error since I upgrade from Odoo 8 to 9.
I use the last commit of Odoo 9, Prestashop 1.6.11, last OCA module and last python package.
I will try to investigate more during the next weeks.

Thanks.

**Comment by smkerz** [comment]
Hello,

I found that commenting the class "ManufacturerExportMapper"
in file
"connector-prestashop/connector_prestashop_catalog_manager/models/product_template/exporter.py" made the trick.

I will try to use like it as pre-production testing.

**Comment by FFernandez-PlanetaTIC** [comment]
Hello,

I'm also having the same problem.

v9.0:
- OCA/OCB@7bcdab309d2eac1f028c8aebc5e5a63216ab99c9 (Fri May 25)
- OCA/connector@caee9b08818f550d18bf0193e21ae3abb3d3c632 (5 commits behind)
- OCA/connector-prestashop@b699a24d51ee2cf9aa16f637082ea8ae6b538961 (last commit)

The code from this line to the end does not make sense to me:
https://github.com/OCA/connector-prestashop/blob/9.0/connector_prestashop_catalog_manager/models/product_template/exporter.py#L273

As @smkerz says, the error disappears if those lines are removed. It's also necessary to change the inheritance in:
https://github.com/OCA/connector-prestashop/blob/9.0/connector_prestashop_manufacturer/models/product_template/exporter.py#L10

This comes from ec90670848f7535b633fb8756da743993b90d53f by @simahawk . Do you think this solution is valid?

Thanks!

**Comment by pedrobaeza** [comment]
I think the problem is that the module requires the module `product_manufacturer` as is (https://github.com/OCA/product-attribute/tree/9.0/product_manufacturer).

**Comment by FFernandez-PlanetaTIC** [comment]
At the end I understand those lines and propose a solution here #97
