### ISSUE TITLE
Prestahop 1.7.4 ?

### ISSUE THREAD

**Issue by devsoft56** [OCA/connector-prestashop#94]
Has anybody tried it on 1.7.4? 
Still only up to 1.6.1?

**Comment by Lazza** [comment]
It seems to work OK-ish if you tweak Prestashop with this fix:
https://www.prestashop.com/forums/topic/763911-ps-17-webservice-order_discounts/?tab=comments#comment-2840998

It probably needs further testing, though, before declaring it's working correctly.

**Comment by paulius-sladkevicius** [comment]
Looks `order_discounts` doesn't exist anymore https://github.com/PrestaShop/PrestaShop/blob/1.7.4.x/classes/webservice/WebserviceRequest.php#L257 and I don't see any alternatives.
