### ISSUE TITLE
[9.0] Catalog manager: link image to URL after export

### ISSUE THREAD

**Issue by FFernandez-PlanetaTIC** [OCA/connector-prestashop#96]
Hi,

I have seen that, after the export of an image, its storage is changed to its URL in Prestashop.

I think that the purpose of catalog manager is to manage products from Odoo and images should be kept there, in Odoo.

We could add a setting in the backend to choose this behavior. What do you think?

Regards.

**Comment by pedrobaeza** [comment]
The management is done on Odoo, but we don't want to duplicate images, and as PrestaShop requires to have the image hosted, this is the less bad situation.
